### ISSUE TITLE
React app.js Error

### ISSUE THREAD

**Issue by tae0code** [TeamCrazyPerformance/LazyPeoplesProject#3]
Express 설치 후 React와 연동을 위해서 
React의 package.json에서 proxy를 설정하고 실행했습니다.

아래와 같은 오류가 발생하는데 해결방법 아시는 고수님들.. 부탁드립니다.
그냥 진짜 맨땅에 헤딩 중인데 어렵네유

```
/Users/tae0code/Documents/Project/Sprint/client/src/App.test.js:1
import React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by tae0code** [comment]
해당 이슈 해결 했습니다.
`npm start`로 시작했을 때 오류가 생겼는데, package.json에서 "," 이걸 하나 더 써놨었습니다.
